# This workflow will do a clean install of node dependencies, build the source code, and publish the compiled code as a Github package
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.1.0
        with:
          always-auth: true
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/
          scope: '@neerinc'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
        working-directory: ./dist
